server:
  port: 8004

eureka:
  instance:
    hostname: zbcn.eureka.security # 主机名称
  client:
    register-with-eureka: false  # 不向注册中心注册自己
    fetch-registry: false # 注册中心的职责就是维护服务实例，所以不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/