spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1 #设置Sleuth的抽样收集概率

server:
  port: 9001

eureka:
  instance:
    # hostname: demo.server # 主机名称
    instance-id: user.server # eureka 服务列表显示名称
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    fetch-registry: true


