server:
  port: 9301
spring:
  application:
    name: admin-security-server
  profiles:
    active: dev
  security:
    user:
      name: zbcn
      password: 123456
  boot:  # 不显示admin-security-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}

