server:
  port: 8401
spring:
  application:
    name: consul-ribbon-server
  profiles:
    active: dev
  cloud:
    consul: #Consul服务注册发现配置
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true #这个必须配
        tags: version=1.0
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        healthCheckInterval: 15s
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
# ribbon 配置
service-url:
  consul-user-service: http://consul-user-service

