spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://github.com/1363653611/config-repo.git
          username: xxxx
          password: xxxxxx
          clone-on-start: true #开启启动时直接从git获取配置
          search-paths: '{application}'
server:
  port: 8901