eureka:
  instance:
    # hostname: demo.server # 主机名称
    instance-id: config.security.server # eureka 服务列表显示名称
  client:
    service-url:
      defaultZone: http://zbcn:123456@localhost:8004/eureka/
    register-with-eureka: true
    fetch-registry: true

