spring:
  application:
    name: config-security-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://github.com/1363653611/config-repo.git
          username: 1363653611
          password: 810@likun
          clone-on-start: true #开启启动时直接从git获取配置
          search-paths: '{application}'
  security: #配置用户名和密码
    user:
      name: zbcn
      password: 123456
server:
  port: 8905