eureka:
  instance:
    # hostname: demo.server # 主机名称
    instance-id: zuul.server # eureka 服务列表显示名称
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
