spring:
  application:
    name: zuul-gateway
  profiles:
    active: dev

# 构建路由地址
zuul:
  prefix: /proxy #给网关路由添加前缀(可选)
  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤
  add-host-header: true #设置为true重定向是会添加host请求头
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  routes: #给服务配置路由
    # 这里可以自定义
    demo-server:
      # 匹配的路由规则: 表示以demo 开头的访问，都将进入 demo-server
      path: /demo/**
      # 路由的目标地址
      #url: http://localhost:9000/
      sericeId: demo-server # 路由的目标服务名


#路由的端点
management:
  endpoints:
    web:
      exposure:
        include: 'routes'
