spring:
  application:
    name: hystrix-server
  profiles:
    active: dev
server:
  port: 8402

eureka:
  instance:
    # hostname: demo.server # 主机名称
    instance-id: hystrix.server-2 # eureka 服务列表显示名称
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream' #暴露hystrix监控端点

# ribbon 配置
service-url:
  user-service: http://user-service